-- ============================================================================
-- Weekly Plans Migration
-- Run this in the Supabase SQL Editor
-- ============================================================================

-- Track which campaign was auto-generated by a weekly plan
ALTER TABLE campaigns ADD COLUMN IF NOT EXISTS weekly_plan_id UUID;

-- ─── Weekly Plans ─────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS weekly_plans (
  id          UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  name        TEXT NOT NULL,
  start_date  DATE NOT NULL, -- Always the Monday of the target week
  status      TEXT DEFAULT 'draft' CHECK (status IN ('draft', 'active', 'completed')),
  created_at  TIMESTAMPTZ DEFAULT now(),
  updated_at  TIMESTAMPTZ DEFAULT now()
);

-- ─── Daily Schedules ──────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS daily_schedules (
  id               UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  weekly_plan_id   UUID REFERENCES weekly_plans(id) ON DELETE CASCADE NOT NULL,
  day_of_week      TEXT NOT NULL CHECK (day_of_week IN ('Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday', 'Sunday')),
  group_id         UUID REFERENCES contact_groups(id) ON DELETE SET NULL,
  template_id      UUID REFERENCES email_templates(id) ON DELETE SET NULL,
  smtp_config_id   UUID REFERENCES smtp_configs(id) ON DELETE SET NULL,
  send_time        TIME DEFAULT '09:00:00',
  send_gap_minutes INTEGER DEFAULT 15,
  gap_jitter_pct   INTEGER DEFAULT 20,
  attachments      JSONB DEFAULT '[]',
  created_at       TIMESTAMPTZ DEFAULT now(),
  updated_at       TIMESTAMPTZ DEFAULT now(),
  UNIQUE (weekly_plan_id, day_of_week)
);

-- ─── RLS ──────────────────────────────────────────────────────────────────────
ALTER TABLE weekly_plans ENABLE ROW LEVEL SECURITY;
ALTER TABLE daily_schedules ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Authenticated access" ON weekly_plans FOR ALL
  TO authenticated USING (true) WITH CHECK (true);

CREATE POLICY "Authenticated access" ON daily_schedules FOR ALL
  TO authenticated USING (true) WITH CHECK (true);

-- ─── Triggers ─────────────────────────────────────────────────────────────────
CREATE TRIGGER weekly_plans_updated_at
  BEFORE UPDATE ON weekly_plans
  FOR EACH ROW EXECUTE FUNCTION update_updated_at();

CREATE TRIGGER daily_schedules_updated_at
  BEFORE UPDATE ON daily_schedules
  FOR EACH ROW EXECUTE FUNCTION update_updated_at();
